/*
 * makechr - make CHR ROM from the VGA font
 *
 * Copyright (c) 2015-2016 Benjamin Gilbert
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include <stdio.h>
#include "font.h"

#define HEIGHT 8

static void write_glyph(int codepoint) {
    int row;

    printf("\n; %d\n.byte ", codepoint);
    for (row = 0; row < HEIGHT; row++) {
        printf("%s$%02x", row ? ", " : "", vgafont8[HEIGHT * codepoint + row]);
    }
    printf("\n.fill %d, 0\n", HEIGHT);
}

int main(int argc, char **argv) {
    int i;

    printf("; Autogenerated by makechr\n");

    for (i = 0; i < 256; i++) {
        write_glyph(i);
    }
}
